# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200000, null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('link_to_website', models.CharField(max_length=200, null=True)),
                ('date_of_issue', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200, null=True)),
                ('number_of_theft', models.IntegerField()),
                ('number_of_murder', models.IntegerField()),
                ('number_of_rape', models.IntegerField()),
                ('number_of_robbery', models.IntegerField()),
                ('number_of_terrorism', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200000, null=True)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('date_of_issue', models.CharField(max_length=200, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_instution', models.CharField(max_length=200, null=True)),
                ('email_id', models.CharField(max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
                ('link_to_website', models.CharField(max_length=200, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Murder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Rape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Robbery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Terrorism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Theft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Complaint')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('admin_priviledge', models.IntegerField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Area')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User'),
        ),
    ]
